/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f7202610192b30cb9cf1db14b44c4975)
interface __BaseEnv_Env {
	DB: D1Database;
	ACTION_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACTION_API_KEY">> {}
}
